name: greet-hello

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: greet-user from local
        run: echo "Hello from GitHub Actions!"

      - name: show current date
        run: echo "$Date"

