name: greet-hello

on:
  schedule:
    - cron: "0 0 * * *" #runs every day at midnight UTC
  #push:
    #branches: [main]

jobs:
  build: # job name
    runs-on: ubuntu-latest

    steps:
      - name: code-checkout
        uses: actions/checkout@v4  # Bring my project code into this machine so I can work on it

      - name: greet-user from local
        run: echo "Hello from GitHub Actions!"

      - name: show current date
        run: date

     # - name: test failed 
        #run: exit 1
         

      - name: print triggered branch
        run: echo "${{ github.ref_name }}" # this is built-in var, that provides the triggered branch name, it only works on push

      - name: list files in repo
        run: ls
      
      - name: print runner OS
        run: echo "runner OS is $RUNNER_OS"

