name: greet-hello

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: code-checkout
        uses: actions/checkout@v4

      - name: greet-user from local
        run: echo "Hello from GitHub Actions!"

      - name: show current date
        run: date

      - name: print triggered branch
        run: echo "${{ github.ref_name }}" # this is built-in var, that provides the triggered branch name, it only works on push

      - name: list files in repo
        run: ls
      
      - name: print runner OS
        run: echo "runner OS is $RUNNER_OS"

