name: trigger-on-pull-request

on:
    pull_request:
        branches: [main]

jobs:
    pr-branch-check:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              run: actions/checkout@v4
            - name: pr-check
              run: |
                BRANCH="${{ github.head_ref }}"
                echo "PR check running for branch $BRANCH" 
